apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: asiayo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: example
  template:
    metadata:
      labels:
        app: example
    spec:
      containers:
      - name: example-container
        image: <asiayo-app-image>
        ports:
        - containerPort: 80
        volumeMounts:
        - name: app-data
          mountPath: /
      volumes:
      - name: app-data
        persistentVolumeClaim:
          claimName: app-pvc
