apiVersion: v1
kind: PersistentVolume
metadata:
  name: app-pv
  namespace: asiayo
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /mnt/data